server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres}
    username: ${DB_USER:postgres.qlciljbuexklxjzxgitk}
    password: ${DB_PASSWORD:BocaPasion11}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

supabase:
  url: ${SUPABASE_URL:https://qlciljbuexklxjzxgitk.supabase.co}
  anon-key: ${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsY2lsamJ1ZXhrbHhqenhnaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzIxNjQsImV4cCI6MjA5MDQ0ODE2NH0.NX038_uwLWXupT21IOUygQlLQwRuT_iSDuti8d1frps}

# Configuración de Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
  show-actuator: true

# Configuracion de Mercado Pago
mercadopago:
  access-token: "TEST-1029377916834190-041508-189529c0e4993743d017da80ae469cc0-597138236" 
  backend-base-url: "https://pps-sk7p.onrender.com"
  frontend-url: "https://overly-mindset-259417.framer.app"
